### PR TITLE
DM-34584: Use samplingSize in setting stamp size

### PR DESCRIPTION
**Pull request by arunkannawadi**

### CODE REVIEW

**Comment by arunkannawadi** [comment]
@jmeyers314 Are these the only fixes required to get the `samplingSize` config right?

**Comment by jmeyers314** [comment]
I think you need to add something to the `_validatePsfCandidates` method too.

**Comment by jmeyers314** [comment]
Other than that, looks good to me.

**Comment by arunkannawadi** [comment]
@jmeyers314 I added the changes to `_validatePsfCandidate` method and improved the tests to include `samplingSize` parameter as well. One thing I'm confused about is whether we should be dividing or multiplying by the `samplingSize` parameter. Note that `samplingSize=0.5` should correspond to 2x oversampling. If I remember right, you had multiplication in your local repo.

**Pull request merged**
